5 add to user registration optionally user avatar.
IgorPrischepa/TFM pull request #10
Opened 2023-04-16 20:56 UTC by IgorPrischepa

Добавил опционально загрузку аватара для пользователя.

2023-04-16 22:19 UTC, IgorPrischepa commented
<img width="722" alt="image" src="https://user-images.githubusercontent.com/5076626/232345765-0450eab5-7566-4a03-84c6-50b083e7aa75.png">
Проверять вот этот коммит.

2023-04-17 04:56 UTC, DiCollars requested changes

2023-04-17 04:56 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/UserService.cs
> +            };
; ?

2023-04-17 04:56 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/UserService.cs
> +                _logger.LogCritical("Role can't be finded. Create new custemer impossible.");
Ну не прям ошибка - но глагол find - он не правильный, то есть у него есть 3 формы, вероятно тебе была нужно тут found

2023-04-17 04:56 UTC, DiCollars commented on tfm.api.dal/Db/Configs/ExampleConfiguration.cs
> +                   .HasForeignKey<ImageFileEntity>(k => k.ExampleId);
Настрой каскадное удаление

2023-04-17 15:03 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/UserService.cs
> +                _logger.LogCritical("Role can't be finded. Create new custemer impossible.");
<img width="655" alt="image" src="https://user-images.githubusercontent.com/5076626/232526416-53f59d3c-f5e5-411c-a8e6-84d30dba23ac.png">
Поправил

2023-04-24 06:52 UTC, DiCollars approved these changes

2023-04-24 09:35 UTC, merged