+ UI model layer (DTO)
IgorPrischepa/TFM pull request #12
Opened 2023-04-17 02:57 UTC by IgorPrischepa

+ Add attributes for DTOs
+ Rename BLL model layer -> "Models"
- Cleanup unnecessary check in BLL

2023-04-17 05:08 UTC, DiCollars requested changes
Хъюстон, запрашиваю изменения, приём.

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Controllers/MasterController.cs
> +        public async Task<IActionResult> DeletePriceAsync([FromQuery] int stylePrice)
Либо /{id} либо FromQuery - вместе не надо. 1 - говорит роут будет выглядить вот так DeletePrice/1 а 2 - что будет выглядеть так DeletePrice?stylePrice=1

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Controllers/ScheduleController.cs
> +        public async Task<IActionResult> DeleteScheduleBlockerAsync([FromQuery] int id)
опять же, FromQuery и получение параметра через роутинг разные штуки, выбери что-то одно

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Controllers/ScheduleController.cs
> +        public async Task<IActionResult> GetMasterBlockersAsync([FromQuery]int id)
Низя FromQuery одновременно с /id

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Controllers/ScheduleController.cs
> +        public async Task<IActionResult> GetScheduleDayAsync([FromQuery]int id)
FromQuery одновременно с /id

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Controllers/StyleController.cs
> +        public async Task<IActionResult> DeleteAsync([FromQuery] int id)
FromQuery с /id

2023-04-17 05:08 UTC, DiCollars commented on tfm.api/Dto/Master/AddMasterExampleDto.cs
> +        public string ShortDescription { get; set; } = string.Empty;
Вообще не очень хорошо когда в бд попадет пустая строка, если там ничего нет лучше ее сделать NULL

2023-04-17 14:00 UTC, IgorPrischepa commented on tfm.api.bll/Models/Schedule/ShowScheduleDto.cs
>  public class ShowScheduleDto
Никак не привыкну :)

2023-04-24 06:46 UTC, DiCollars approved these changes

2023-04-24 06:48 UTC, merged