1 masters schedule
IgorPrischepa/TFM pull request #9
Opened 2023-04-14 02:39 UTC by IgorPrischepa

Реализованы методы для задания даты и времени работы мастера в конкретный день недели.
Добавлена возможность задать промежуток когда мастер не может принимать закакзы.

2023-04-15 21:39 UTC, DiCollars requested changes

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +public class ScheduleService : IScheduleService
Можем закрывать имплиментации модификатором internal - все равно передаем зависимости только интерфейсы - если доступа не хватит в api, можно сделать DI-инжектор на уровне bll (если еще не сделали).

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        return await _schedule.AddAsync(new ScheduleEntity
Сейчас не меняй, но надо потом настроить маппер для подобных мест. Будет удобнее.

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        return await _schedule.AddAsync(new ScheduleEntity
Но только маппер тоже надо будет конфигурировать, точно не помню - но вроде если не указывать конкретные фроммемберы - он под капотом работает на рефлексии

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (scheduleId <= 0) throw new ArgumentOutOfRangeException(nameof(scheduleId));
Во многих местах такая проверка - может стоит сделать сервис валидатор, пусть валидирует DTO

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (blockerDto.StartDateTime >= blockerDto.EndDateTime)
Вот тут тоже можно все это сделать в валидаторе - и например использовать паттерн Шаблонный метод (Template Method) - пополнишь свою коллекцию знаний новым поведенческим паттерном, почитать тут - https://metanit.com/sharp/patterns/3.4.php

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.dal/Db/Configs/ScheduleConfiguration.cs
> +        builder.HasOne(_ => _.Master).WithMany();
Пропиши полностью, укажи навигационное свойство в WithMany и HasForeignKey и  OnDelete

2023-04-15 21:39 UTC, DiCollars commented on tfm.api.dal/Entities/ScheduleBlockerEntity.cs
> +    public string Reason { get; set; } = "Can't work at this day";
Подобные текстовые константы лучше выносить в отдельный класс с константами

2023-04-15 21:39 UTC, DiCollars commented on tfm.api/Program.cs
> +const string tableName = "logs";
Можно отдельно в файлик констант вынести

2023-04-15 21:54 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +public class ScheduleService : IScheduleService
Да, забыл о том, что нужно повышать постепенно видимость. Поправил во всех сервисах

2023-04-15 21:57 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (scheduleId <= 0) throw new ArgumentOutOfRangeException(nameof(scheduleId));
Я это сделал на случай, если всё же в сервис пытаются что-то засунуть не то.

2023-04-15 22:12 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +public class ScheduleService : IScheduleService
Оказалось область видимости тут оправдана 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/5076626/232255316-3c7a3647-ce77-47ee-8313-1dd50abe0220.png">

2023-04-15 22:13 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        return await _schedule.AddAsync(new ScheduleEntity
Задачка с маппером по позже у нас. Пока не брался

2023-04-15 22:13 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (blockerDto.StartDateTime >= blockerDto.EndDateTime)
Не очень понимаю как он применим тут.

2023-04-15 22:18 UTC, IgorPrischepa commented on tfm.api.dal/Db/Configs/ScheduleConfiguration.cs
> +        builder.HasOne(_ => _.Master).WithMany();
<img width="525" alt="image" src="https://user-images.githubusercontent.com/5076626/232255483-d1208a01-cc9e-4051-a758-fd822a451c25.png">
Связь нормально создаётся. Почему так нельзя?

2023-04-15 22:35 UTC, DiCollars commented on tfm.api.dal/Db/Configs/ScheduleConfiguration.cs
> +        builder.HasOne(_ => _.Master).WithMany();
> <img width="525" alt="image" src="https://user-images.githubusercontent.com/5076626/232255483-d1208a01-cc9e-4051-a758-fd822a451c25.png">
> Связь нормально создаётся. Почему так нельзя?

Ну она и без настройки через флюент апи создастся, так нагляднее и каскадное удаление настроим не дефолтное

2023-04-15 22:36 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +public class ScheduleService : IScheduleService
> Оказалось область видимости тут оправдана 
> <img width="564" alt="image" src="https://user-images.githubusercontent.com/5076626/232255316-3c7a3647-ce77-47ee-8313-1dd50abe0220.png">
> 

Сделай инжектор

2023-04-15 22:37 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (scheduleId <= 0) throw new ArgumentOutOfRangeException(nameof(scheduleId));
> Я это сделал на случай, если всё же в сервис пытаются что-то засунуть не то. 

Да и я говорю что можно сделать ещё один сервис - валидатор, он будет валидировать входные дто, чтобы не дублировать код все время, у тебя в каждом методе проверка в иф, по сути одинаковая.

2023-04-15 22:40 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (blockerDto.StartDateTime >= blockerDto.EndDateTime)
> Не очень понимаю как он применим тут.

Ну если сделать дополнительный сервис валидатор и в нем проверку DTO, не везде проверка одинаковая, где то она расширенная, так вот чтобы ее расширить и не дублировать код, можно обратиться к этому паттерну. Возможно он тут избыточен, но ради практики стоит попробовать.

2023-04-15 23:34 UTC, IgorPrischepa commented on tfm.api/Program.cs
> +const string tableName = "logs";
Вынес имя таблицы в appsettings.json

2023-04-15 23:35 UTC, IgorPrischepa commented on tfm.api.dal/Entities/ScheduleBlockerEntity.cs
> +    public string Reason { get; set; } = "Can't work at this day";
Вынес в отдельный класс

2023-04-15 23:35 UTC, IgorPrischepa commented on tfm.api.dal/Db/Configs/ScheduleConfiguration.cs
> +        builder.HasOne(_ => _.Master).WithMany();
Сделяль

2023-04-15 23:35 UTC, IgorPrischepa commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (blockerDto.StartDateTime >= blockerDto.EndDateTime)
Почитал статью, не понял как этот паттерн ложиться на эту ситуацию.

2023-04-16 20:40 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (scheduleId <= 0) throw new ArgumentOutOfRangeException(nameof(scheduleId));
Сделаем по другому, опишу отдельной задачей.

2023-04-16 20:41 UTC, DiCollars commented on tfm.api.bll/Services/Implementations/ScheduleService.cs
> +        if (blockerDto.StartDateTime >= blockerDto.EndDateTime)
Сделаем по другому, опишу отдельной задачей. (Тут все таки паттерн плохо применим)

2023-04-16 20:47 UTC, DiCollars approved these changes

2023-04-16 20:48 UTC, merged